manage side - create message:
fintegrate-practicom/workers pull request #74
Opened 2024-06-03 20:26 UTC by AvigailH

2024-06-04 09:21 UTC, chanakamin requested changes
עבודה יפה ומקיפה מאוד!!

2024-06-04 09:21 UTC, chanakamin commented on workers-backend/src/main.ts
> +  await app.listen(5001);
תורידי את השינוי הזה.

2024-06-04 09:21 UTC, chanakamin commented on workers-backend/src/message/controllers/messages.controller.ts
> +    @Put('/')
אמור לכלול id של message כחלק מה route

2024-06-04 09:21 UTC, chanakamin commented on workers-backend/src/message/controllers/messages.controller.ts
> +        const updatedMessage = await this.messageService.updateMessage(message);
try / catch?

2024-06-04 09:21 UTC, chanakamin commented on workers-backend/src/message/controllers/messages.controller.ts
> +        return await this.messageService.getMessages();
יש להוסיף ווידוא של המשתמש

2024-06-04 09:21 UTC, chanakamin commented on workers-backend/src/message/controllers/messages.controller.ts
> +        const addMessage = await this.messageService.addMessage(message);
try / catch?

2024-06-04 09:21 UTC, chanakamin commented on workers-backend/src/message/services/messages.service.ts
> +      return await this.messageModel.findByIdAndUpdate(message._id, message, { new: true }).exec();
ה _id אמור להתקבל כפרמטר נוסף בפונקציה.
ה message לא אמור לכלול אותו, אלא את המשתנים שאותם הולכים לעדכן בלבד.

2024-06-15 20:02 UTC, AvigailH commented on workers-backend/src/message/controllers/messages.controller.ts
> +    @Put('/')
יש בת שאחראית על הפונקציה הזו 
מחקתי אותה מהקבצים

2024-06-18 09:41 UTC, MichalAmir approved these changes

2024-06-18 10:33 UTC, MichalAmir approved these changes

2024-06-22 23:13 UTC, chanakamin commented on workers-backend/src/schemas/message.entity.ts
> +  message_id: number;
הייתי מורידה את זה.
אמורים להשתמש ב id הדיפולטיבי שמונגו נותן

2024-06-22 23:13 UTC, chanakamin commented on workers-frontend/src/App.tsx
> +      <h1>hello</h1>
יש למחוק את השינויים מהקובץ הזה

2024-06-22 23:14 UTC, chanakamin requested changes
מצוין.
תודירי רק את השינויים מה app, וכן תשני את השימוש ב id של ה message. זה לא מאפיין שמגיע מהקליינט, זה מונגו יוצר לבד.

2024-06-24 10:11 UTC, chanakamin approved these changes

2024-06-24 10:27 UTC, merged