New task send rabbit ayala sari
fintegrate-practicom/workers pull request #75
Opened 2024-06-04 08:53 UTC by AyalaZelivansky

2024-06-04 09:26 UTC, chanakamin commented on workers-backend/src/rabbit-publisher/rabbit-publisher.service.ts
> +  private readonly nameExchange: string = 'message_queue';
זה שינוי בכל המקומות? זהה גם ב communication?

2024-06-04 09:31 UTC, chanakamin requested changes
כתוב ממש יפה ורמת קוד יפה

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/tasks/service/tasks.service.ts
> +    );
לא שולפים ואז מפלטרים, אמורים לשלוח שאילתה לצונגו שהוא יחזיר רק את היוזר הרצוי

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/tasks/service/tasks.service.ts
> +
ומה קורה אם אין יוזר ומנהל?
זה לא אמור לזרוק שגיאה?

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/tasks/service/tasks.service.ts
> +      pattern: 'message_queue',
לא עדיף שאת המידע הזה לא כל מקום ישלח אלא ה publisher בעצמו ידע להוסיף?

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/tasks/service/tasks.service.ts
> +
עדיף להפוך את הסדר, קודם ליצור ואחר כך לשלוח

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/tasks/service/tasks.service.ts
> +        to: foundUser.userEmail,
הייתי מצפה ל type מסודר לדבר הזה

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/user/controllers/users.controller.ts
> +    return this.usersService.findAll();
? את מה זה משרת?

2024-06-04 09:31 UTC, chanakamin commented on workers-backend/src/user/services/users.service.ts
> +    const employees = await this.userModel.find().exec();
לא חושבת שנכון שתהיה קריאה כזו. מינימום שיהיה לפי business id.
אפשר לעשות קריאה שמחזירה user לפי id

2024-06-04 09:37 UTC, saribar commented on workers-backend/src/rabbit-publisher/rabbit-publisher.service.ts
> +  private readonly nameExchange: string = 'message_queue';
בcommunication זה בלי exchange רק עם queue, לא ברור לנו אם כשאני משתמשת  בpublish  בexchange זה מחייב גם בהקשר לcommunication כי הבת שעשתה את הcommunication לא הבינה את זה כך

2024-06-04 10:44 UTC, chanakamin commented on workers-backend/src/rabbit-publisher/rabbit-publisher.service.ts
> +  private readonly nameExchange: string = 'message_queue';
נכון, בצד של ה communication לא צריך exchange. לא שמתי לב לזה קודם.

2024-06-04 10:50 UTC, saribar commented on workers-backend/src/tasks/service/tasks.service.ts
> +      pattern: 'message_queue',
אין בעיה, רק שכך הוא ישלח תמיד לאותו queue
זה נכון?

2024-06-17 22:07 UTC, chanakamin commented on workers-backend/src/schemas/task.entity.ts
> +  employeeId: string;
ObjectId

2024-06-17 22:10 UTC, chanakamin approved these changes
אני מאשרת כי זה מצוין וכמעט מושלם.

אשמח שתתיחסי לפני מרג לשתי הערות: שינוי טייפ של ה employeeId, וכן ביצירת משימה לזרוק שגיאה אם אין מנהל או משתמש

2024-06-17 23:36 UTC, saribar approved these changes

2024-06-17 23:51 UTC, saribar approved these changes

2024-06-17 23:51 UTC, merged