employee sign up process - update details
fintegrate-practicom/workers pull request #78
Opened 2024-06-04 14:07 UTC by tamarfridlis

2024-06-17 22:10 UTC, chanakamin commented on workers-backend/src/schemas/user.entity.ts
> +  id: string;
מה המשמעות?

2024-06-17 22:13 UTC, chanakamin commented
זה נראה שבתהליך העדכון שלך דרסת קוד של בנות אחרות, תוודאי שכל הקטעים שנמחקים אצלך באמת אמורים להימחק, ותסדרי גם קונפליקטים

2024-06-18 06:54 UTC, tamarfridlis commented on workers-backend/src/schemas/user.entity.ts
> +  id: string;
הid הזה הוא אותו דבר כמו הid של הemployee זה אותה רשומה לאותו עובד והם תואמים ה-idים

2024-06-18 09:23 UTC, chanakamin requested changes
תעדכני את ה try catch שהורדת בפונקציות של ה worker service

2024-06-18 09:23 UTC, chanakamin commented on workers-backend/src/schemas/user.entity.ts
> +  id: string;
זה id של היוזר? לא צריך להוסיף מונגו מוסיף

2024-06-18 09:23 UTC, chanakamin commented on workers-backend/src/worker/controllers/workers.controller.ts
> +      throw new HttpException(error, HttpStatus.INTERNAL_SERVER_ERROR);
לא תמיד זה internal server error
שימי לב שבכזה מצב אז גם אם קודם נזרק שיוזר לא נמצא פתאום כאן ייזרק לו שגיאת שרת

2024-06-18 09:23 UTC, chanakamin commented on workers-backend/src/worker/services/workers.service.ts
> +    return employees;
למה הורדת try catch?

2024-06-23 10:35 UTC, chanakamin submitted a review, later dismissed

2024-06-25 22:08 UTC, chanakamin submitted a review, later dismissed
מצוין

2024-06-26 14:51 UTC, efratBurshtein approved these changes
מהממם!

2024-06-26 14:51 UTC, merged